services:
  # PostgreSQL Database
  - type: pserv
    name: oilseed-db
    databaseName: hedge_db
    user: alok
    plan: free

  # Backend API Service
  - type: web
    name: oilseed-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oilseed-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: PYTHONPATH
        value: /app

  # Frontend Application
  - type: web
    name: oilseed-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: oilseed-backend
          property: host
      - key: NODE_ENV
        value: production
